# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Hongze ZHAO
email: hongze.zhao(a)gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I'm not willing to be labeled with 'programmer'. Yes, I am a software engineer
   but I also love photography, tennis, hiking ... I am a real man in diversity. :)
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://grandpa.red" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
